server:
  port: 8083
  servlet:
    context-path: /customer-app

spring:
  application:
    name: ms-customer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/CUSTOMER_DB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update

  rabbit:
    spring:
      rabbitmq:
        dynamic=true:
    host: localhost
    port: 15672
    username: guest
    password: guest


feign:
  merchant:
    list-menu:
      url: http://localhost:8081/merchant-app/product

